"""add coluna de categoria id em produtos

Revision ID: 83f4ef8f8de9
Revises: 850595299dce
Create Date: 2026-04-10 12:57:54.149945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f4ef8f8de9'
down_revision: Union[str, Sequence[str], None] = '850595299dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produtos', 'categorias', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('produtos', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'category_id')
    # ### end Alembic commands ###
