"""add payment id

Revision ID: c43b2ecb9e7e
Revises: 5980a2e1c998
Create Date: 2026-01-15 10:56:10.197233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43b2ecb9e7e'
down_revision: Union[str, Sequence[str], None] = '5980a2e1c998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'payment_id')
    # ### end Alembic commands ###
