"""empty message

Revision ID: ee2e381f5e40
Revises: 427d0a9f8ee8
Create Date: 2026-01-11 23:14:29.478260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2e381f5e40'
down_revision: Union[str, Sequence[str], None] = '427d0a9f8ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrinhos', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrinhos', sa.Column('value', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
